AIRTHMETIC

In [37]:
import numpy as np

In [38]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
a1
a2


array([ 6,  7,  8,  9, 10])

In [39]:
sum=a1+a2
sum

array([ 7,  9, 11, 13, 15])

In [40]:
sub=a1-a2
sub

array([-5, -5, -5, -5, -5])

In [41]:
mul=a1*a2
mul

array([ 6, 14, 24, 36, 50])

In [42]:
div=a1/a2
div

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [43]:
floor_div=a1//a2
floor_div

array([0, 0, 0, 0, 0])

In [44]:
exponent=a1**a2
exponent

array([      1,     128,    6561,  262144, 9765625])

BROADCASTING

In [45]:
l = [10, 20, 30, 40, 50]
arr = np.array(l)
arr

array([10, 20, 30, 40, 50])

In [46]:
for i in arr:
    print(i+100)

110
120
130
140
150


In [47]:
arr + 10

array([20, 30, 40, 50, 60])

Deep and Shallow copy

In [48]:
arr2 = np.arange(1,26).reshape(5,5) 
arr2       

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [49]:
arr2 + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [50]:
arr2*2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

In [51]:
a = np.arange(1, 21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [52]:
slice = a[:5]
slice * 10

array([10, 20, 30, 40, 50])

In [53]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [54]:
a[4:9] * 10


array([50, 60, 70, 80, 90])

In [55]:
a
b = a.copy()

In [56]:
b[0]=100

In [57]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [58]:
b

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

Matrix operation

In [63]:
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])


In [64]:
A

array([[1, 2],
       [3, 4]])

In [65]:
B

array([[5, 6],
       [7, 8]])

In [ ]:
A @ B

array([[19, 22],
       [43, 50]])

In [67]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])