In [41]:
import numpy as np

In [ ]:
arr= np.array([1, 2, 3,4,5,6,7,8,9,10])
arr

In [ ]:
a=[[1,2,3],[4,5,6],[7,8,9]]
a

In [ ]:
np.array(a)

Array Generation Function

In [ ]:
np.arange(1,11,2)

In [ ]:
np.arange(2,12,2)

In [ ]:
np.zeros((3,4)) 

In [ ]:
arr = np.ones((10,10))
arr

In [ ]:
np.linspace(1,5,10)    

Random Generation Function

In [ ]:
np.random.rand(5)

In [ ]:
np.random.randn(10)

In [28]:
np.random.randint(10,20,10)

array([13, 12, 17, 13, 16, 10, 19, 12, 12, 15], dtype=int32)

Array Attributes

In [31]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
arr.shape

(3, 3)

In [33]:
arr.size

9

In [34]:
arr.dtype

dtype('int64')

Array Methods

In [37]:
arr.min()


np.int64(1)

In [36]:
arr.max()

np.int64(9)

In [39]:
arr.sum()

np.int64(45)

In [44]:
np.sum(arr,axis = 0)

array([12, 15, 18])

In [49]:
np.sum(arr,axis = 1)

array([ 6, 15, 24])

In [51]:
arr.mean()

np.float64(5.0)

In [52]:
arr.std()

np.float64(2.581988897471611)

In [53]:
arr.argmax()

np.int64(8)

In [55]:
arr.argmin()

np.int64(0)

Reshaping And Resizing

In [60]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [62]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])