Numpy Indexing And Slicing Of Vectors

In [38]:
import numpy as np

In [39]:
arr =np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [40]:
arr[9]

np.int64(20)

In [41]:
arr[2:9]

array([13, 14, 15, 16, 17, 18, 19])

In [42]:
arr[2:9:2]

array([13, 15, 17, 19])

In [43]:
arr_slice=arr[3::2]
arr_slice


array([14, 16, 18, 20])

In [44]:
arr[9]

np.int64(20)

Numpy Indexing And Slicing Of Matrix

In [45]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [46]:
arr[5]

array([26, 27, 28, 29, 30])

In [47]:
arr[5,4]

np.int64(30)

In [48]:
arr[0,2]

np.int64(3)

In [49]:
slice=arr[2:5,3:5]
slice

array([[14, 15],
       [19, 20],
       [24, 25]])

In [50]:
slice1=arr[0:3,0:3]
slice1

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

In [51]:
slice4=arr[3:6,0:3]
slice4

array([[16, 17, 18],
       [21, 22, 23],
       [26, 27, 28]])

In [52]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

Boolean Indexing

In [53]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [54]:
bool_index = arr%2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [55]:
arr=arr[bool_index]
arr

array([12, 14, 16, 18, 20])